export const userType = {
  SET_LOADING_USER: "SET_LOADING_USER",
  ADD_USER_DATA: "ADD_USER_DATA",
  SET_ERROR_USER: "SET_ERROR_USER",

  SET_LOADING_LOGIN: "SET_LOADING_LOGIN",
  ADD_USER_LOGIN: "ADD_USER_LOGIN",
  ADD_USER_LOGOUT: "ADD_USER_LOGOUT",
  SET_ERROR_LOGIN: "SET_ERROR_LOGIN",
};
