export const movieType = {
  SET_LOADING_SERIES: "SET_LOADING_SERIES",
  POPULATE_DATA_SERIES: "POPULATE_DATA_SERIES",
  SET_ERROR_SERIES: "SET_ERROR_SERIES",

  SET_LOADING_MOVIE: "SET_LOADING_MOVIE",
  POPULATE_DATA_MOVIE: "POPULATE_DATA_MOVIE",
  SET_ERROR_MOVIE: "SET_ERROR_MOVIE",

  SET_LOADING_DETAIL: "SET_LOADING_DETAIL",
  POPULATE_DATA_DETAIL: "POPULATE_DATA_DETAIL",
  SET_ERROR_DETAIL: "SET_ERROR_DETAIL",

  SET_LOADING_SEARCH: "SET_LOADING_SEARCH",
  POPULATE_DATA_SEARCH: "POPULATE_DATA_SEARCH",
  SET_ERROR_SEARCH: "SET_ERROR_SEARCH",
};
